"""Restore models and add Demo fields

Revision ID: 5622a97791dc
Revises: add_pwd_history
Create Date: 2026-01-19 20:18:48.123081

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5622a97791dc"
down_revision = "add_pwd_history"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("password_history", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_password_history_user_id"))

    with op.batch_alter_table("system_config", schema=None) as batch_op:
        batch_op.alter_column(
            "value",
            existing_type=sa.VARCHAR(length=100),
            type_=sa.String(length=255),
            existing_nullable=False,
        )
        batch_op.drop_constraint(batch_op.f("system_config_key_key"), type_="unique")
        batch_op.drop_column("id")

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "is_guest",
                sa.Boolean(),
                nullable=False,
                server_default=sa.text("false"),
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("is_guest")

    with op.batch_alter_table("system_config", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False)
        )
        batch_op.create_unique_constraint(
            batch_op.f("system_config_key_key"),
            ["key"],
            postgresql_nulls_not_distinct=False,
        )
        batch_op.alter_column(
            "value",
            existing_type=sa.String(length=255),
            type_=sa.VARCHAR(length=100),
            existing_nullable=False,
        )

    with op.batch_alter_table("password_history", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_password_history_user_id"), ["user_id"], unique=False
        )

    # ### end Alembic commands ###
