"""Ensure SystemConfig table

Revision ID: 87c5d6b3f863
Revises: 5622a97791dc
Create Date: 2026-01-19 21:42:52.716761

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "87c5d6b3f863"
down_revision = "5622a97791dc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Validation: Check if table exists before creating to prevent errors if manually created
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    tables = inspector.get_table_names()

    if "system_config" not in tables:
        op.create_table(
            "system_config",
            sa.Column("key", sa.String(length=50), nullable=False),
            sa.Column("value", sa.String(length=255), nullable=False),
            sa.PrimaryKeyConstraint("key"),
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("system_config")
    # ### end Alembic commands ###
