"""Initial migration

Revision ID: f6ce5bc614e8
Revises: 
Create Date: 2026-01-09 01:43:37.464111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6ce5bc614e8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('student_id', sa.String(length=20), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('consented_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_student_id'), ['student_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=64), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('ipa', sa.String(length=64), nullable=True),
    sa.Column('vowels', sa.String(length=64), nullable=True),
    sa.Column('stressed_vowel', sa.String(length=10), nullable=True),
    sa.Column('audio_path', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('text')
    )
    op.create_table('submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('test_type', sa.String(length=10), nullable=True),
    sa.Column('file_path', sa.String(length=256), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analysis_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('f1_raw', sa.Float(), nullable=True),
    sa.Column('f2_raw', sa.Float(), nullable=True),
    sa.Column('f1_ref', sa.Float(), nullable=True),
    sa.Column('f2_ref', sa.Float(), nullable=True),
    sa.Column('scaling_factor', sa.Float(), nullable=True),
    sa.Column('f1_norm', sa.Float(), nullable=True),
    sa.Column('f2_norm', sa.Float(), nullable=True),
    sa.Column('distance_hz', sa.Float(), nullable=True),
    sa.Column('distance_bark', sa.Float(), nullable=True),
    sa.Column('is_deep_voice_corrected', sa.Boolean(), nullable=True),
    sa.Column('is_outlier', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('analysis_results')
    op.drop_table('submissions')
    op.drop_table('words')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_student_id'))

    op.drop_table('users')
    # ### end Alembic commands ###
